import { TestDefinition } from '../types';

export const TEST_REGISTRY: TestDefinition[] = [
  {
    id: 'color-sweep',
    title: 'Color & Dead Pixels',
    subtitle: 'Check for dead or stuck pixels across the display',
    iconName: 'color-palette-outline',
    category: 'Screen & Touch',
  },
  {
    id: 'touch-grid',
    title: 'Touch Responsiveness',
    subtitle: 'Glide your finger across the screen to test touch precision',
    iconName: 'hand-left-outline',
    category: 'Screen & Touch',
  },
  {
    id: 'multi-touch',
    title: 'Multi-Touch',
    subtitle: 'Place multiple fingers on the glass to verify multi-point touch',
    iconName: 'finger-print-outline',
    category: 'Screen & Touch',
  },
  {
    id: 'accelerometer',
    title: 'Accelerometer',
    subtitle: 'Shake or tilt the phone to verify the 3-axis motion sensor',
    iconName: 'speedometer-outline',
    category: 'Motion & Sensors',
    autoPass: true,
  },
  {
    id: 'compass',
    title: 'Compass',
    subtitle: 'Rotate the phone and watch heading update in real-time',
    iconName: 'compass-outline',
    category: 'Motion & Sensors',
    autoPass: true,
  },
  {
    id: 'proximity',
    title: 'Proximity Sensor',
    subtitle: 'Cover the top sensor notch with your hand to test detection',
    iconName: 'ear-outline',
    category: 'Motion & Sensors',
  },
  {
    id: 'front-camera',
    title: 'Front Camera',
    subtitle: 'Check the TrueDepth/selfie camera for focus and clarity',
    iconName: 'camera-reverse-outline',
    category: 'Camera',
  },
  {
    id: 'rear-camera',
    title: 'Rear Camera',
    subtitle: 'Check the main lens system for clarity and sensor response',
    iconName: 'camera-outline',
    category: 'Camera',
  },
  {
    id: 'flashlight',
    title: 'Flashlight / Torch',
    subtitle: 'Toggle the rear LED True Tone flash to verify hardware',
    iconName: 'flashlight-outline',
    category: 'Camera',
  },
  {
    id: 'speaker',
    title: 'Speaker',
    subtitle: 'Play pure acoustic test tones across standard frequencies',
    iconName: 'volume-high-outline',
    category: 'Audio',
  },
  {
    id: 'microphone',
    title: 'Microphone',
    subtitle: 'Speak or clap near the phone to measure live audio decibels',
    iconName: 'mic-outline',
    category: 'Audio',
    autoPass: true,
  },
  {
    id: 'biometrics',
    title: 'Face ID / Touch ID',
    subtitle: 'Authenticate with Apple Secure Enclave biometrics',
    iconName: 'scan-outline',
    category: 'Biometrics',
    autoPass: true,
  },
  {
    id: 'gps',
    title: 'Location & GPS',
    subtitle: 'Verify satellite signal acquisition and precision coordinates',
    iconName: 'navigate-outline',
    category: 'Connectivity',
    autoPass: true,
  },
  {
    id: 'wifi',
    title: 'Wi-Fi Network',
    subtitle: 'Verify wireless interface and local subnet connection',
    iconName: 'wifi-outline',
    category: 'Connectivity',
    autoPass: true,
  },
  {
    id: 'bluetooth',
    title: 'Bluetooth',
    subtitle: 'Verify Bluetooth controller status and peripheral radio',
    iconName: 'bluetooth-outline',
    category: 'Connectivity',
  },
  {
    id: 'storage',
    title: 'Storage & Memory',
    subtitle: 'Read internal flash storage capacity and partition metrics',
    iconName: 'server-outline',
    category: 'Hardware',
    autoPass: true,
  },
  {
    id: 'vibration',
    title: 'Taptic Engine',
    subtitle: 'Test Apple Taptic Engine feedback at different intensities',
    iconName: 'radio-outline',
    category: 'Hardware',
  },
  {
    id: 'volume-buttons',
    title: 'Volume Buttons',
    subtitle: 'Confirm mechanical click feedback for Volume Up and Down',
    iconName: 'musical-notes-outline',
    category: 'Hardware',
  },
  {
    id: 'mute-switch',
    title: 'Ring / Silent Switch',
    subtitle: 'Confirm the physical mute toggle or Action button',
    iconName: 'notifications-off-outline',
    category: 'Hardware',
  },
  {
    id: 'power-button',
    title: 'Side / Lock Button',
    subtitle: 'Lock screen then wake device to test power switch detection',
    iconName: 'power-outline',
    category: 'Hardware',
    autoPass: true,
  },
];
