import { TestDefinition } from '../types';

export const TEST_REGISTRY: TestDefinition[] = [
  {
    id: 'color-sweep',
    title: 'Color & Dead Pixels',
    subtitle: 'Check for dead or stuck pixels across the display',
    icon: '🎨',
    category: 'Screen & Touch',
  },
  {
    id: 'touch-grid',
    title: 'Touch Responsiveness',
    subtitle: 'Tap each zone to verify the touchscreen responds everywhere',
    icon: '✋',
    category: 'Screen & Touch',
  },
  {
    id: 'multi-touch',
    title: 'Multi-Touch',
    subtitle: 'Use multiple fingers simultaneously to verify multi-touch works',
    icon: '🖐',
    category: 'Screen & Touch',
  },
  {
    id: 'accelerometer',
    title: 'Accelerometer',
    subtitle: 'Shake the phone to verify the motion sensor is working',
    icon: '📳',
    category: 'Motion & Sensors',
    autoPass: true,
  },
  {
    id: 'compass',
    title: 'Compass',
    subtitle: 'Rotate the phone and watch the heading update in real-time',
    icon: '🧭',
    category: 'Motion & Sensors',
    autoPass: true,
  },
  {
    id: 'proximity',
    title: 'Proximity Sensor',
    subtitle: 'Cover the top sensor with your hand — screen should dim',
    icon: '👁',
    category: 'Motion & Sensors',
    autoPass: true,
  },
  {
    id: 'front-camera',
    title: 'Front Camera',
    subtitle: 'Check the selfie camera for focus, clarity, and distortion',
    icon: '🤳',
    category: 'Camera',
  },
  {
    id: 'rear-camera',
    title: 'Rear Camera',
    subtitle: 'Check the rear camera for focus, clarity, and distortion',
    icon: '📸',
    category: 'Camera',
  },
  {
    id: 'flashlight',
    title: 'Flashlight / Torch',
    subtitle: 'The rear torch will turn on — confirm it lights up',
    icon: '🔦',
    category: 'Camera',
  },
  {
    id: 'speaker',
    title: 'Speaker',
    subtitle: 'A test tone will play — listen for clarity, distortion, or silence',
    icon: '🔊',
    category: 'Audio',
  },
  {
    id: 'microphone',
    title: 'Microphone',
    subtitle: 'Speak into the phone and watch the live level meter respond',
    icon: '🎙',
    category: 'Audio',
    autoPass: true,
  },
  {
    id: 'biometrics',
    title: 'Face ID / Touch ID',
    subtitle: 'Authenticate using biometrics to confirm the sensor is working',
    icon: '🔐',
    category: 'Biometrics',
    autoPass: true,
  },
  {
    id: 'gps',
    title: 'GPS',
    subtitle: 'The phone will attempt to get a GPS fix — accuracy shown live',
    icon: '📍',
    category: 'Connectivity',
    autoPass: true,
  },
  {
    id: 'wifi',
    title: 'Wi-Fi',
    subtitle: 'Checks if the phone is connected to a Wi-Fi network',
    icon: '📶',
    category: 'Connectivity',
    autoPass: true,
  },
  {
    id: 'bluetooth',
    title: 'Bluetooth',
    subtitle: 'Scans for nearby Bluetooth devices to confirm the radio works',
    icon: '🔵',
    category: 'Connectivity',
    autoPass: true,
  },
  {
    id: 'storage',
    title: 'Storage',
    subtitle: 'Reports total and available storage on the device',
    icon: '💾',
    category: 'Hardware',
    autoPass: true,
  },
  {
    id: 'vibration',
    title: 'Vibration',
    subtitle: 'The phone will vibrate — confirm you feel it',
    icon: '📳',
    category: 'Hardware',
  },
  {
    id: 'volume-buttons',
    title: 'Volume Buttons',
    subtitle: 'Press Vol Up then Vol Down — confirm both buttons click and respond',
    icon: '🔉',
    category: 'Hardware',
  },
  {
    id: 'mute-switch',
    title: 'Mute Switch',
    subtitle: 'Toggle the mute/ring switch — the indicator below will update live',
    icon: '🔕',
    category: 'Hardware',
    autoPass: true,
  },
  {
    id: 'power-button',
    title: 'Power / Lock Button',
    subtitle: 'Press the side button to lock, then unlock — confirm it works',
    icon: '⚡',
    category: 'Hardware',
    autoPass: true,
  },
];
